package ai.tabforge.workshop.orchestrator;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import ai.tabforge.workshop.agent.ProgressReporter;
import ai.tabforge.workshop.agent.SubAgent;
import ai.tabforge.workshop.model.Finding;
import ai.tabforge.workshop.model.HumanDecision;
import ai.tabforge.workshop.model.ReviewScope;

/**
 * The central coordinator of the Workshop review — manages all sub-agents,
 * enforces workflow, handles lifecycle hooks, and decides when to escalate.
 *
 * <p>
 * Analogy: like a project manager who receives a large contract, breaks it into
 * work packages, assigns each to a specialist, monitors progress, collects
 * reports, and escalates to the client only when a decision requires human
 * judgment. The specialists (sub-agents) do the technical work; the
 * orchestrator coordinates and decides what happens next.
 * </p>
 *
 * <p>
 * This class is the core learning artifact for the "Agentic Architecture &
 * Orchestration" exam domain (27%) - Domain 1, from <a href=
 * "https://everpath-course-content.s3-accelerate.amazonaws.com/instructor%2F8lsy243ftffjjy1cx9lm3o2bw%2Fpublic%2F1773274827%2FClaude+Certified+Architect+%E2%80%93+Foundations+Certification+Exam+Guide.pdf">Claude
 * Certified Architect – Foundations Certification Exam Guide</a>
 * 
 * Every pattern described in the certification guide is implemented here.
 * </p>
 *
 * <p>
 * Review lifecycle (the "agentic loop"):
 * <ol>
 * <li>INIT: receive ReviewScope from StartReviewTool MCP call</li>
 * <li>DECOMPOSE: TaskDecomposer splits project into agent-specific chunks</li>
 * <li>DISPATCH: for each sub-agent: fire onBeforeAgent() hook, then
 * execute()</li>
 * <li>COLLECT: receive AgentResult; fire onAfterAgent() hook</li>
 * <li>EVALUATE: SelfEvaluatorAgent checks output quality; retry if
 * insufficient</li>
 * <li>ESCALATE: EscalationHandler checks for CRITICAL — pause if found</li>
 * <li>AGGREGATE: AgentResultAggregator merges all findings</li>
 * <li>COMPLETE: store ReviewReport, mark session as done</li>
 * </ol>
 * </p>
 * 
 * This behavior is implemented in the startReview() method of this class.
 *
 * @see TaskDecomposer for how the project is split into reviewable chunks
 * @see ContextWindowManager for how token limits are respected per agent call
 * @see EscalationHandler for the human-in-the-loop decision logic
 * @see AgentResultAggregator for how findings from all agents are merged
 */

public class OrchestratorAgent implements ProgressReporter{
	/*
	 * list of active sessions - agents jobs. startReview() will write there, the
	 * getStatus() will read from here. The key for this map is the reviewId
	 * generated by the startReview() methos
	 */
	private Map<String, ReviewSession> activeSessions = new ConcurrentHashMap<>();

	/**
	 * Starts a new review session asynchronously and returns immediately with a
	 * reviewId. Called by StartReviewTool explicitly, which creates and passes to this method the
	 * {@code ReviewScope} record instance, based on JSON from Claude AI, for
	 * example:
	 * <pre><code>
	 * { "project_path": "C:/project", "scope": "changed_files", "focus": "all" }
	 * </code></pre>
	 * 
	 * Here is chain of calls describing how this method is called:
	 * <pre><code>
	 * - Developer: "Review my changes before PR" 
	 * - Claude: → undersand intent, and  calls StartReviewTool(projectPath, scope) 
	 * -StartReviewTool: → create ReviewScope
	 *                    → calls OrchestratorAgent.startReview(scope) → returns {
	 *                      reviewId: "abc-123" } without waiting to Claude AI
	 *</code></pre>
	 * <p>
	 * Analogy: like submitting a job to Java's ExecutorService — you get a Future
	 * (reviewId) immediately; the work runs in the background. The MCP caller
	 * (Claude AI) does not block waiting for results.
	 * </p>
	 * 
	 *
	 * @param scope ReviewScope defining project path and review depth
	 * @return reviewId (UUID) used by all subsequent tool calls - StartReviewTool returns this value to Claude AI
	 */

	public String startReview(ReviewScope scope) {
		return UUID.randomUUID().toString();
	}

	/**
	 * Read content from the activeSessions.
	 * 
	 * The caller (Claude AI) polls {@code GetReportTool} for completion. We do not
	 * write any polling loop in the code in order for GetReportTool to be called .
	 * We do not send instructions to Claude at runtime. We just describe the
	 * GetReportTool well - and Claude deduces from the tool description himself the
	 * logic of when and how to use it. On the other side, we must call this method
	 * explicitly in the GetReportTool.
	 * 
	 * Here is chain of call for this method:
	 * <pre><code>
	 * Developer: "Review my changes before PR" 
       Claude AI:                 → calls StartReviewTool(projectPath, scope) 
       StartReviewTool:   → create ReviewScope 
                             → calls OrchestratorAgent.startReview(scope) 
                             → returns { reviewId: "abc-123" } without waiting to Claude AI
       Claude AI:                 → waits a moment, then calls GetReportTool("abc-123") 
       GetReportTool:     → returns { status: "RUNNING", progress: "SecurityAuditor 60%" } 
       Claude AI:                 → calls GetReportTool again a little later 
       GetReportTool:     → returns { status: "COMPLETED", report: {...} } 
       Claude AI:                 → presents findings to the developer in natural language. This is because of GetReportTool description part:
                                    "If status is COMPLETED, present the findings to the developer."
       </code></pre>
	 * 
	 * @param reviewId
	 * @return : <pre><code>
	 *           RUNNING : Review is currently running — agents are executing
	 *           AWAITING_HUMAN : Review is paused — a CRITICAL finding requires human input
	 *           COMPLETED : Review completed successfully — report is final.
	 *           CANCELLED : Review was cancelled by the developer 
	 *           FAILED : Review    failed due to an unrecoverable error
	 *          </code></pre>
	 *         {@code GetReportTool} returns different JSON to the Claude AI based
	 *         on which state the review is in — running progress vs. final report
	 *         vs. escalation request
	 * 
	 */
	public ReviewSession getStatus(String reviewId) {
		return activeSessions.get(reviewId);
	}
	
	 /**
	  * Will be called by the {@link SubAgent#execute()} during file processing,
	  * to push live progress data into the {@code ReviewSession} .
	  *
	  * <p>CERTIFICATION NOTE — Domain 1: Agentic Architecture &amp; Orchestration (27%):
	  * Covers Task Statement 1.7: <em>"Manage session state, resumption, and forking"</em>.
	  * This method is the session state update mechanism — the agent pushes progress
	  * into the session while it runs, so GetReportTool can always return current state
	  * without polling the agent. State is maintained in the orchestrator, not in the agent.
	  * </p>
	  *
	  *   Let say, OrchestratorAgent (this class) starts SecurityAuditorAgent in the startReview() method.
      <pre><code>   

      │
      │  agent processes file by file
      │  for each file it starts processing:
      │
      ▼
   
      for (Path file : context.getFileList()) {

        // HERE: let's inform the orchestrator which file we are processing now:
         context.getOrchestrator().updateProgress(context.getReviewId(), file.getFileName().toString());

         // we analyze the file — we call the Claude API:
         List<Finding> findings = analyzeFile(file);

         // we are collecting results:
         allFindings.addAll(findings);
      }
      </code></pre>
      - - - -
      
       So when Claude AI calls GetReportTool — the data is already  in the {@code ReviewSession}. GetReportTool only reads the current state  

	  * @param reviewId
	  * @param currentFile
	  */
	 @Override
	  public void updateProgress(String reviewId, String currentFile) {
	      ReviewSession session = activeSessions.get(reviewId);
	      session.setCurrentlyProcessedFile(currentFile);
	      session.setProcessedFiles(session.getProcessedFiles() + 1);
	  }
	 
		@Override
		public void escalate(String reviewId, Finding finding) {
			
		}


	/**
	 * Resumes a paused review after the developer has responded to an escalation.
	 *
	 * <p>
	 * Called by: RespondToEscalationTool when the developer makes a decision in
	 * Claude Desktop about a CRITICAL finding.
	 * </p>
	 *
	 * @param reviewId the paused session to resume
	 * @param decision ACCEPT_FIX / REJECT_FINDING / OVERRIDE_CONTINUE
	 */
	public void resumeAfterEscalation(String reviewId, HumanDecision decision) {
		// TODO:
	}

}
