package ai.tabforge.workshop.orchestrator;

import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.anthropic.client.AnthropicClient;
import com.anthropic.client.okhttp.AnthropicOkHttpClient;

import ai.tabforge.workshop.agent.AgentContext;
import ai.tabforge.workshop.agent.ProgressReporter;
import ai.tabforge.workshop.agent.SubAgent;
import ai.tabforge.workshop.agents.ArchitectureCheckerAgent;
import ai.tabforge.workshop.agents.PerformanceAnalystAgent;
import ai.tabforge.workshop.agents.SecurityAuditorAgent;
import ai.tabforge.workshop.agents.TransactionAnalystAgent;
import ai.tabforge.workshop.model.AgentResult;
import ai.tabforge.workshop.model.AgentSummary;
import ai.tabforge.workshop.model.EscalationRequest;
import ai.tabforge.workshop.model.Finding;
import ai.tabforge.workshop.model.HumanDecision;
import ai.tabforge.workshop.model.ReviewReport;
import ai.tabforge.workshop.model.ReviewScope;
import ai.tabforge.workshop.model.Severity;

/**
 * The central coordinator of the Workshop review — manages all sub-agents,
 * enforces workflow, handles lifecycle hooks, and decides when to escalate.
 *
 * <p>
 * Analogy: like a project manager who receives a large contract, breaks it into
 * work packages, assigns each to a specialist, monitors progress, collects
 * reports, and escalates to the client only when a decision requires human
 * judgment. The specialists (sub-agents) do the technical work; the
 * orchestrator coordinates and decides what happens next.
 * </p>
 *
 * <p>
 * This class is the core learning artifact for the "Agentic Architecture &
 * Orchestration" exam domain (27%) - Domain 1, from <a href=
 * "https://everpath-course-content.s3-accelerate.amazonaws.com/instructor%2F8lsy243ftffjjy1cx9lm3o2bw%2Fpublic%2F1773274827%2FClaude+Certified+Architect+%E2%80%93+Foundations+Certification+Exam+Guide.pdf">Claude
 * Certified Architect – Foundations Certification Exam Guide</a>
 * 
 * Every pattern described in the certification guide is implemented here.
 * </p>
 *
 * <p>
 * Review lifecycle (the "agentic loop"):
 * <ol>
 * <li>INIT: receive ReviewScope from StartReviewTool MCP call</li>
 * <li>DECOMPOSE: TaskDecomposer splits project into agent-specific chunks</li>
 * <li>DISPATCH: for each sub-agent: fire onBeforeAgent() hook, then
 * execute()</li>
 * <li>COLLECT: receive AgentResult; fire onAfterAgent() hook</li>
 * <li>EVALUATE: SelfEvaluatorAgent checks output quality; retry if
 * insufficient</li>
 * <li>ESCALATE: escalate() checks for CRITICAL — pause if found</li>
 * <li>AGGREGATE: AgentResultAggregator merges all findings</li>
 * <li>COMPLETE: store ReviewReport, mark session as done</li>
 * </ol>
 * </p>
 * 
 * This behavior is implemented in the startReview() method of this class.
 *
 * <p>Created by: {@code WorkshopServer.start()} — a single instance is created at server
 * startup and shared across all MCP tool calls. It is injected into each tool:
 * <pre><code>
 * OrchestratorAgent orchestrator = new OrchestratorAgent();
 * tools.add(new StartReviewTool(orchestrator).toolSpecification(jsonMapper));
 * tools.add(new GetReportTool(orchestrator).toolSpecification(jsonMapper));
 * tools.add(new RespondToEscalationTool(orchestrator).toolSpecification(jsonMapper));
 * </code></pre>
 * This ensures all tools share the same {@code activeSessions} map — StartReviewTool
 * writes a session, GetReportTool reads it, RespondToEscalationTool modifies it.</p>
 *
 * @see TaskDecomposer for how the project is split into reviewable chunks
 * @see ContextWindowManager for how token limits are respected per agent call
 * @see #escalate(String, Finding) for the human-in-the-loop decision logic
 * @see AgentResultAggregator for how findings from all agents are merged
 */

public class OrchestratorAgent implements ProgressReporter{
	private static final Logger logger = LoggerFactory.getLogger(OrchestratorAgent.class);
	/*
	 * list of active sessions - agents jobs. startReview() will write there, the
	 * getStatus() will read from here. The key for this map is the reviewId
	 * generated by the startReview() methos
	 */
	private Map<String, ReviewSession> activeSessions = new ConcurrentHashMap<>();
    private final ExecutorService executor = Executors.newCachedThreadPool();
    private final TaskDecomposer decomposer = new TaskDecomposer();

	/**
	 * Starts a new review session asynchronously and returns immediately with a
	 * reviewId. Called by StartReviewTool explicitly, which creates and passes to this method the
	 * {@code ReviewScope} record instance, based on JSON from Claude AI, for
	 * example:
	 * <pre><code>
	 * { "project_path": "C:/project", "scope": "changed_files", "focus": "all" }
	 * </code></pre>
	 * 
	 * Here is chain of calls describing how this method is called:
	 * <pre><code>
	 * - Developer: "Review my changes before PR" 
	 * - Claude: → undersand intent, and  calls StartReviewTool(projectPath, scope) 
	 * -StartReviewTool: → create ReviewScope
	 *                    → calls OrchestratorAgent.startReview(scope) → returns {
	 *                      reviewId: "abc-123" } without waiting to Claude AI
	 *</code></pre>
	 * But, before returning the result to Claude AI, this method starts the agents execution in background threads, collects their results, and stores them in a review session.
	 * 
	 * 
	 * <p>
	 * Analogy: like submitting a job to Java's ExecutorService — you get a Future
	 * (reviewId) immediately; the work runs in the background. The MCP caller
	 * (Claude AI) does not block waiting for results.
	 * </p>
	 * 
	 * <p>
	 *   GetReportTool will periodically check status, by calling getStatus() from this class - see getStatus() javaDoc for an explanation of how this method is ensured to be called by GetReportTool.
	 *   The state in the ReviewSession is changed in two ways: 1. by the agents that are working  (by calling the updateProgress() method from this class), 2. as well as in this method itself.
	 * </>
	 * 
	 *
	 * @param scope ReviewScope defining project path and review depth
	 * @return reviewId (UUID) used by all subsequent tool calls - StartReviewTool returns this value to Claude AI
	 */

	public String startReview(ReviewScope scope) {
		String reviewId =  UUID.randomUUID().toString();
		
		ReviewSession session = new ReviewSession(reviewId,  scope, ReviewReport.ReviewStatus.RUNNING,
				null, // ReviewReport
				null, // EscalationRequest
				Instant.now().toString());
	      activeSessions.put(reviewId, session);
	      
	      executor.submit(() -> {
	          try {
	              Map<Class<? extends SubAgent>, List<Path>> agentWork = decomposer.decompose(scope);
                  // list of results of each agent:
	              List<AgentResult> results = new ArrayList<>();
	              // statistic to be included in ReviewReport (number of filesScanned, criticalCount etc..)
	              // Key is agent name:
	              Map<String, AgentSummary> summaries = new HashMap<>();

	              for (Map.Entry<Class<? extends SubAgent>, List<Path>> entry : agentWork.entrySet()) {
	                  // proveri da nije cancelovano izmedju agenata
	                  if (session.getStatus() == ReviewReport.ReviewStatus.CANCELLED) return;

	                  AgentContext context = new AgentContext(
	                      scope.projectPath(), entry.getValue(), reviewId, 4096);
	                  SubAgent agent = createAgent(entry.getKey());
	                  // call the agent:
	                  AgentResult result = agent.execute(context); // list of Findings for this agent etc...
	                  results.add(result);

	                  summaries.put(result.agentName(), new AgentSummary(
	                      result.agentName(),
	                      entry.getValue().size(),
	                      result.findings().size(),
	                      (int) result.findings().stream()
	                          .filter(f -> f.severity() == Severity.CRITICAL).count(),
	                      result.inputTokens(),
	                      result.outputTokens(),
	                      result.durationMs(),
	                      result.retryCount()
	                  ));
	              }

	              List<Finding> allFindings = results.stream()
	                  .flatMap(r -> r.findings().stream())
	                  .collect(Collectors.toList());

	              Severity overallRisk = allFindings.stream()
	                  .map(Finding::severity)
	                  .min(Comparator.comparingInt(Severity::ordinal))
	                  .orElse(Severity.INFO);

	              boolean safeToMerge = allFindings.stream()
	                  .noneMatch(f -> f.severity() == Severity.CRITICAL);

	              session.setReport(new ReviewReport(
	                  reviewId,
	                  scope.projectPath().toString(),
	                  session.getStartedAt(),
	                  Instant.now().toString(),
	                  ReviewReport.ReviewStatus.COMPLETED,
	                  overallRisk,
	                  safeToMerge,
	                  allFindings,
	                  summaries,
	                  List.of()  // humanDecisions — prazno za Phase 1
	              ));
	              session.setStatus(ReviewReport.ReviewStatus.COMPLETED);

	          } catch (Exception e) {
	              session.setStatus(ReviewReport.ReviewStatus.FAILED);
	              logger.error("Review failed, reviewId={}", reviewId, e);
	          }
	      });	      
	      return reviewId;
	}
	
	private SubAgent createAgent(Class<? extends SubAgent> agentClass) {
	      AnthropicClient client = AnthropicOkHttpClient.builder()
	              .apiKey(System.getenv("ANTHROPIC_API_KEY"))
	              .build();

	          if (agentClass == SecurityAuditorAgent.class) return new SecurityAuditorAgent(this, client);
	          if (agentClass == TransactionAnalystAgent.class) return new TransactionAnalystAgent(this, client);
	          if (agentClass == PerformanceAnalystAgent.class) return new PerformanceAnalystAgent(this, client);
	          if (agentClass == ArchitectureCheckerAgent.class) return new ArchitectureCheckerAgent(this, client);

	          throw new IllegalArgumentException("Unknown agent class: " + agentClass.getName());
	}

	/**
	 * Read content from the activeSessions.
	 *
	 * <p> 
	 * The caller (Claude AI) polls {@code GetReportTool} for completion. We do not
	 * write any polling loop in the code in order for GetReportTool to be called .
	 * We do not send instructions to Claude at runtime. We just describe the
	 * GetReportTool well - and Claude deduces from the tool description himself the
	 * logic of when and how to use it. IMPORTANT: On the other side, we must call this method
	 * explicitly in the GetReportTool, and that behaviour is implemented in GetReportTool.toolSpecification(), 
	 * more precise, in GetReportTool.execute(). The GetReportTool.toolSpecification() is the method which returns the
	 * McpServerFeatures.AsyncToolSpecification, which is required when registering MCP tool with
	 *  io.modelcontextprotocol.server.McpServer. 
	 *  It is a mechanism that ensures that this very method is called when GetReportTool is triggered by Claude AI.
	 * </p>
	 * 
	 * Here is chain of call for this method:
	 * <pre><code>
	 * Developer: "Review my changes before PR" 
       Claude AI:                 → calls StartReviewTool(projectPath, scope) 
       StartReviewTool:   → create ReviewScope 
                             → calls OrchestratorAgent.startReview(scope) 
                             → returns { reviewId: "abc-123" } without waiting to Claude AI
       Claude AI:                 → waits a moment, then calls GetReportTool("abc-123") 
       GetReportTool:     → returns { status: "RUNNING", progress: "SecurityAuditor 60%" } 
       Claude AI:                 → calls GetReportTool again a little later 
       GetReportTool:     → returns { status: "COMPLETED", report: {...} } 
       Claude AI:                 → presents findings to the developer in natural language. This is because of GetReportTool description part:
                                    "If status is COMPLETED, present the findings to the developer."
       </code></pre>
	 * 
	 * @param reviewId
	 * @return : <pre><code>
	 *           RUNNING : Review is currently running — agents are executing
	 *           AWAITING_HUMAN : Review is paused — a CRITICAL finding requires human input
	 *           COMPLETED : Review completed successfully — report is final.
	 *           CANCELLED : Review was cancelled by the developer 
	 *           FAILED : Review    failed due to an unrecoverable error
	 *          </code></pre>
	 *         {@code GetReportTool} returns different JSON to the Claude AI based
	 *         on which state the review is in — running progress vs. final report
	 *         vs. escalation request
	 * 
	 */
	public ReviewSession getStatus(String reviewId) {
		return activeSessions.get(reviewId);
	}
	
	 /**
	  * Will be called by the {@link SubAgent#execute()} during file processing,
	  * to push live progress data into the {@code ReviewSession} .
	  *
	  * <p>CERTIFICATION NOTE — Domain 1: Agentic Architecture &amp; Orchestration (27%):
	  * Covers Task Statement 1.7: <em>"Manage session state, resumption, and forking"</em>.
	  * This method is the session state update mechanism — the agent pushes progress
	  * into the session while it runs, so GetReportTool can always return current state
	  * without polling the agent. State is maintained in the orchestrator, not in the agent.
	  * </p>
	  *
	  *   Let say, OrchestratorAgent (this class) starts SecurityAuditorAgent in the startReview() method.
      <pre><code>   

      │
      │  agent processes file by file
      │  for each file it starts processing:
      │
      ▼
   
      for (Path file : context.getFileList()) {

        // HERE: let's inform the orchestrator which file we are processing now:
         context.getOrchestrator().updateProgress(context.getReviewId(), file.getFileName().toString());

         // we analyze the file — we call the Claude API:
         List<Finding> findings = analyzeFile(file);

         // we are collecting results:
         allFindings.addAll(findings);
      }
      </code></pre>
      - - - -
      
       So when Claude AI calls GetReportTool — the data is already  in the {@code ReviewSession}. GetReportTool only reads the current state  

	  * @param reviewId
	  * @param currentFile
	  */
	 @Override
	  public void updateProgress(String reviewId, String currentFile) {
	      ReviewSession session = activeSessions.get(reviewId);
	      session.setCurrentlyProcessedFile(currentFile);
	      session.setProcessedFiles(session.getProcessedFiles() + 1);
	  }
	 
	 /**
	  * 
	  */
	  @Override
	  public void escalate(String reviewId, Finding finding) {
	      ReviewSession session = activeSessions.get(reviewId);

	      // 1. kreira pitanje — standardno ili sa napomenom o nesigurnosti
	      String question = finding.confidence() >= 0.85
	          ? EscalationRequest.standardQuestion(finding)
	          : EscalationRequest.uncertaintyQuestion(finding);

	      // 2. kreira EscalationRequest i upisuje u session
	      EscalationRequest escalation = new EscalationRequest(
	          reviewId, finding, question,
	          List.of(HumanDecision.DecisionType.ACCEPT_FIX,
	                  HumanDecision.DecisionType.REJECT_FINDING,
	                  HumanDecision.DecisionType.OVERRIDE_CONTINUE),
	          Instant.now().toString(),
	          null
	      );
	      session.setPendingEscalation(escalation);
	      session.setStatus(ReviewReport.ReviewStatus.AWAITING_HUMAN);

	      // 3. pravi latch i čuva ga — resumeAfterEscalation() će pozvati countDown()
	      // It needs to be stored in the session, because that way it can be retrieved in resumeAfterEscalation() 
	      CountDownLatch latch = new CountDownLatch(1);
	      session.setLatch(latch);

	      // 4. blocks the agent thread until the developer responds - This thread will wait until the latch drops to 0:
	      try {
	          latch.await();
	      } catch (InterruptedException e) {
	          Thread.currentThread().interrupt();
	          session.setStatus(ReviewReport.ReviewStatus.FAILED);
	      }
	  }

	/**
	 * Resumes a paused review after the developer has responded to an escalation.
	 * Blocked agent thread - {@link SubAgent#execute()} - can continue working
	 * (was previously blocked by escalate() method call, from SubAgent.execute() )
	 *
	 * <p>
	 * Called by: RespondToEscalationTool when the developer makes a decision in
	 * Claude Desktop about a CRITICAL finding.
	 * </p>
	 *
	 * @param reviewId the paused session to resume
	 * @param decision ACCEPT_FIX / REJECT_FINDING / OVERRIDE_CONTINUE .
	 *              Created and passed here by the RespondToEscalationTool 
	 */
	  public void resumeAfterEscalation(String reviewId, HumanDecision decision) {
	      ReviewSession session = activeSessions.get(reviewId);

	      if (decision.decisionType() == HumanDecision.DecisionType.CANCEL) {
	          session.setStatus(ReviewReport.ReviewStatus.CANCELLED);
	      } else {
	          // ACCEPT_FIX / REJECT_FINDING / OVERRIDE_CONTINUE — review nastavlja
	          session.setStatus(ReviewReport.ReviewStatus.RUNNING);
	          session.setPendingEscalation(null); // GetReportTool no longer returns AWAITING_HUMAN 
	      }
          // now, unlocks a blocked agent thread:  
	      session.getLatch().countDown(); 
	  }
}
